#!/bin/bash

url=$1
title=$2

echo $url
echo $title

mkdir -p .tmp

wget --adjust-extension --span-hosts --convert-links --backup-converted \
     --no-directories --timestamping --page-requisites \
     --directory-prefix=.tmp \
     $url

page=$(echo $url | awk -F '/' '{print $NF}')
page=$(ls .tmp/$page{,.htm,.html})

ebook-convert $page epub/$title.epub
ebook-convert $page mobi/$title.mobi

rm -r .tmp

